/**
 * Seed Data for Streaming Website
 *
 * Used by seed.ts to populate the database.
 */

export const ADMIN_CREDENTIALS = {
  name: "Admin User",
  email: "admin@example.com",
  password: "admin123",
};

export const GENRES = [
  { name: "Action", slug: "action" },
  { name: "Adventure", slug: "adventure" },
  { name: "Biography", slug: "biography" },
  { name: "Comedy", slug: "comedy" },
  { name: "Crime", slug: "crime" },
  { name: "Drama", slug: "drama" },
  { name: "Fantasy", slug: "fantasy" },
  { name: "History", slug: "history" },
  { name: "Horror", slug: "horror" },
  { name: "Sci-Fi", slug: "sci-fi" },
  { name: "Thriller", slug: "thriller" },
];

export const MOVIES = [
  {
    title: "Dune: Part Two",
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future only he can foresee.",
    thumbnail: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8Py05Nxl1X.jpg",
    duration: 166,
    embedUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    embedType: "youtube",
    releaseYear: 2024,
    rating: "8.5",
    featured: true,
    status: "active",
    genres: ["sci-fi", "action", "adventure", "drama"],
  },
  {
    title: "Oppenheimer",
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II. A epic biographical thriller that explores the complex moral dilemmas faced by the father of the atomic age.",
    thumbnail: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    duration: 180,
    embedUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
    embedType: "youtube",
    releaseYear: 2023,
    rating: "8.9",
    featured: true,
    status: "active",
    genres: ["drama", "biography", "history"],
  },
  {
    title: "The Batman",
    description:
      "When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    thumbnail: "https://image.tmdb.org/t/p/original/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fber9Tav5PXS5qG4.jpg",
    duration: 176,
    embedUrl: "https://www.youtube.com/embed/mqqft2x_Aa4",
    embedType: "youtube",
    releaseYear: 2022,
    rating: "8.1",
    featured: true,
    status: "active",
    genres: ["action", "crime", "drama"],
  },
  {
    title: "Interstellar",
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth becomes increasingly uninhabitable due to crop blights and dust storms.",
    thumbnail: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    duration: 169,
    embedUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    embedType: "youtube",
    releaseYear: 2014,
    rating: "8.7",
    featured: false,
    status: "active",
    genres: ["sci-fi", "drama", "adventure"],
  },
  {
    title: "Inception",
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    thumbnail: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    poster: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep9B9iMrXfs.jpg",
    duration: 148,
    embedUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    embedType: "youtube",
    releaseYear: 2010,
    rating: "8.8",
    featured: false,
    status: "active",
    genres: ["sci-fi", "action", "thriller"],
  },
  {
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    thumbnail: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    duration: 152,
    embedUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
    embedType: "youtube",
    releaseYear: 2008,
    rating: "9.0",
    featured: false,
    status: "active",
    genres: ["action", "crime", "drama"],
  },
  {
    title: "Avatar: The Way of Water",
    description:
      "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    thumbnail: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmPA.jpg",
    duration: 192,
    embedUrl: "https://www.youtube.com/embed/d9MyW72ELq0",
    embedType: "youtube",
    releaseYear: 2022,
    rating: "7.8",
    featured: false,
    status: "active",
    genres: ["sci-fi", "action", "adventure"],
  },
  {
    title: "John Wick: Chapter 4",
    description:
      "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    thumbnail: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    duration: 169,
    embedUrl: "https://www.youtube.com/embed/qEVUtrk8_B4",
    embedType: "youtube",
    releaseYear: 2023,
    rating: "8.2",
    featured: false,
    status: "active",
    genres: ["action", "crime", "thriller"],
  },
  {
    title: "Spider-Man: No Way Home",
    description:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    thumbnail: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    duration: 148,
    embedUrl: "https://www.youtube.com/embed/JfVOs4VSpmA",
    embedType: "youtube",
    releaseYear: 2021,
    rating: "8.4",
    featured: false,
    status: "active",
    genres: ["action", "adventure", "sci-fi"],
  },
  {
    title: "Top Gun: Maverick",
    description:
      "After thirty years, Maverick is still pushing the envelope as a top naval aviator. He must train a group of Top Gun graduates for a specialized mission while confronting his past.",
    thumbnail: "https://image.tmdb.org/t/p/original/6tDt7zN35WDmC8BrqRr7o2QYYfp.jpg",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    duration: 131,
    embedUrl: "https://www.youtube.com/embed/qSqVVqeaDqU",
    embedType: "youtube",
    releaseYear: 2022,
    rating: "8.3",
    featured: false,
    status: "active",
    genres: ["action", "drama"],
  },
];

export const SERIES = [
  {
    title: "House of the Dragon",
    description:
      "The Targaryen civil war, known as the Dance of the Dragons, begins when King Viserys I breaks with tradition by naming his daughter Rhaenyra heir to the Iron Throne. The kingdom is torn apart as families choose sides.",
    thumbnail: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    firstAiredYear: 2022,
    lastAiredYear: null,
    rating: "8.5",
    featured: true,
    status: "ongoing",
    genres: ["drama", "fantasy", "action"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description:
          "The Targaryen dynasty is at the absolute apex of its power, but the seeds of destruction have already been planted.",
        thumbnail: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        releaseYear: 2022,
        episodeCount: 3,
        episodes: [
          {
            episodeNumber: 1,
            duration: 66,
            embedUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 54,
            embedUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 3,
            duration: 62,
            embedUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
      {
        seasonNumber: 2,
        title: "Season 2",
        description: "The Dance of the Dragons begins as the blacks and the greens go to war.",
        thumbnail: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        releaseYear: 2024,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 61,
            embedUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 59,
            embedUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "The Last of Us",
    description:
      "Twenty years after a fungal outbreak ravages the planet, survivors Joel and Ellie embark on a brutal journey through the US to find a possible cure. What begins as a small job becomes a brutal cross-country journey.",
    thumbnail: "https://image.tmdb.org/t/p/original/AjTcJWslCFvGlQr4ZGuDaZmZRAA.jpg",
    poster: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    firstAiredYear: 2023,
    lastAiredYear: null,
    rating: "8.8",
    featured: true,
    status: "ongoing",
    genres: ["drama", "action", "adventure"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description: "Joel and Ellie journey across a post-apocalyptic America.",
        thumbnail: "https://image.tmdb.org/t/p/original/AjTcJWslCFvGlQr4ZGuDaZmZRAA.jpg",
        releaseYear: 2023,
        episodeCount: 3,
        episodes: [
          {
            episodeNumber: 1,
            duration: 81,
            embedUrl: "https://www.youtube.com/embed/ittT7ZblKvM",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 53,
            embedUrl: "https://www.youtube.com/embed/ittT7ZblKvM",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 3,
            duration: 76,
            embedUrl: "https://www.youtube.com/embed/ittT7ZblKvM",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "Breaking Bad",
    description:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future. Partnering with a former student, he descends into the criminal underworld.",
    thumbnail: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    firstAiredYear: 2008,
    lastAiredYear: 2013,
    rating: "9.5",
    featured: false,
    status: "completed",
    genres: ["drama", "crime", "thriller"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description:
          "Walter White, a chemistry teacher, discovers that he has cancer and decides to enter the drug trade to provide for his family.",
        thumbnail: "https://image.tmdb.org/t/p/w500/gFZjCcQ6eIvHdJLYCdyA83mFLQc.jpg",
        releaseYear: 2008,
        episodeCount: 3,
        episodes: [
          {
            episodeNumber: 1,
            duration: 58,
            embedUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 48,
            embedUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 3,
            duration: 48,
            embedUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
      {
        seasonNumber: 2,
        title: "Season 2",
        description:
          "Walter and Jesse continue their drug operation while facing personal and professional complications.",
        thumbnail: "https://image.tmdb.org/t/p/w500/2BHmx5AZvHanS2qwoq9Nu4VkaH5.jpg",
        releaseYear: 2009,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 48,
            embedUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 48,
            embedUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "Game of Thrones",
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia. Based on the bestselling book series by George R.R. Martin.",
    thumbnail: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    firstAiredYear: 2011,
    lastAiredYear: 2019,
    rating: "8.4",
    featured: false,
    status: "completed",
    genres: ["drama", "fantasy", "action"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description: "Winter is coming as noble families wage war for the Iron Throne.",
        thumbnail: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        releaseYear: 2011,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 62,
            embedUrl: "https://www.youtube.com/embed/rlR4PJn8b8I",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 56,
            embedUrl: "https://www.youtube.com/embed/rlR4PJn8b8I",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "Stranger Things",
    description:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl. A love letter to the '80s classics that captivated a generation.",
    thumbnail: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    firstAiredYear: 2016,
    lastAiredYear: null,
    rating: "8.7",
    featured: false,
    status: "ongoing",
    genres: ["drama", "fantasy", "horror"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description:
          "A young boy vanishes, leading to the discovery of a mystery involving supernatural forces.",
        thumbnail: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        releaseYear: 2016,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 47,
            embedUrl: "https://www.youtube.com/embed/b9EkMc79ZSU",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 55,
            embedUrl: "https://www.youtube.com/embed/b9EkMc79ZSU",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "The Witcher",
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts. But when destiny hurtles him toward a powerful sorceress and a young princess, the three must navigate the increasingly volatile Continent together.",
    thumbnail: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    firstAiredYear: 2019,
    lastAiredYear: null,
    rating: "8.0",
    featured: false,
    status: "ongoing",
    genres: ["drama", "fantasy", "action"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description:
          "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny.",
        thumbnail: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
        releaseYear: 2019,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 61,
            embedUrl: "https://www.youtube.com/embed/ndl1W4ltcmg",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 60,
            embedUrl: "https://www.youtube.com/embed/ndl1W4ltcmg",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "Wednesday",
    description:
      "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart and solve the mystery that embroiled her parents. All while navigating her new relationships at Nevermore Academy.",
    thumbnail: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    firstAiredYear: 2022,
    lastAiredYear: null,
    rating: "8.2",
    featured: false,
    status: "ongoing",
    genres: ["comedy", "crime", "fantasy"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description:
          "Wednesday Addams investigates a murder mystery while attending Nevermore Academy.",
        thumbnail: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        releaseYear: 2022,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 50,
            embedUrl: "https://www.youtube.com/embed/Di310WS8zLk",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 48,
            embedUrl: "https://www.youtube.com/embed/Di310WS8zLk",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
  {
    title: "The Mandalorian",
    description:
      "After the fall of the Empire, a lone gunfighter makes his way through the outer reaches of the lawless galaxy. He is hired to retrieve a child, but ends up protecting him from those who wish to harm him.",
    thumbnail: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    poster: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    firstAiredYear: 2019,
    lastAiredYear: null,
    rating: "8.5",
    featured: false,
    status: "ongoing",
    genres: ["action", "adventure", "sci-fi"],
    seasons: [
      {
        seasonNumber: 1,
        title: "Season 1",
        description: "The Mandalorian travels to the outer reaches of the galaxy.",
        thumbnail: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
        releaseYear: 2019,
        episodeCount: 3,
        episodes: [
          {
            episodeNumber: 1,
            duration: 40,
            embedUrl: "https://www.youtube.com/embed/aOC8E8k_rNw",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 35,
            embedUrl: "https://www.youtube.com/embed/aOC8E8k_rNw",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 3,
            duration: 38,
            embedUrl: "https://www.youtube.com/embed/aOC8E8k_rNw",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
      {
        seasonNumber: 2,
        title: "Season 2",
        description: "The Mandalorian and the Child continue their journey.",
        thumbnail: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
        releaseYear: 2020,
        episodeCount: 2,
        episodes: [
          {
            episodeNumber: 1,
            duration: 42,
            embedUrl: "https://www.youtube.com/embed/aOC8E8k_rNw",
            embedType: "youtube",
            status: "active",
          },
          {
            episodeNumber: 2,
            duration: 36,
            embedUrl: "https://www.youtube.com/embed/aOC8E8k_rNw",
            embedType: "youtube",
            status: "active",
          },
        ],
      },
    ],
  },
];
